name: Wingify Engineering
description: This is the engineering blog from the hackers at Wingify
keywords: wingify, ab testing, split testing

highligher:  pygments
safe:        true
timezone:    Asia/Kolkata
future:      true
permalink:   /posts/:title/
paginate:    5

authors:
 ankit_jain:
  twitter: ankneo
 sparsh_gupta:
  twitter: sparshgupta
 kushagra_agarwal:
  twitter: kushsolitary
 himanshu_kapoor:
  twitter: himkp
 kushagra_gour:
  twitter: chinchang457
 vivek_kishore:
  twitter:
 rohit_yadav:
  twitter: _bhaisaab
 vaidik_kapoor:
  twitter: vaidikkapoor
 suchit_puri:
  twitter: suchitpuri
 rahul_jain:
  twitter: rahuljain12
 kamal_sahni:
  twitter: kamalsahni1
 apoorv_saxena:
  twitter: apoorv_saxena
 hemkaran_raghav:
  twitter: hemkaranraghav
 dheeraj_joshi:
  twitter: dheerajhere
 jatin_makhija_ankita_gupta:
  twitter: NotJustBond
 dinkar_pundir:
  twitter: dinkarpundir
 rachit:
  twitter: squiroid
 sahilbatla:
  twitter: sahilbathla
 varun_malhotra:
  twitter: s0ftvar
 amandeep_singh:
  twitter: aman1064
 chhavi_khandelwal:
  twitter: chhavikhandelw1
 sahil_goyal:
  twitter: sahil91
 ashish_bardhan:
  twitter: CreativeBakchod
 surbhi_mahajan:
  twitter: surbhi_mahajan
 aditya_mishra_punit_gupta:
  twitter: Aditya_r_m
 shubham_soni_udit_chawla:
  twitter: shubhamSoni92
 varun_pk:
  twitter: varun0x1