name: Wingify Engineering
description: This is the engineering blog from the hackers at Wingify
keywords: wingify, ab testing, split testing

highligher:  pygments
safe:        true
timezone:    Asia/Kolkata
future:      true
permalink:   /posts/:title/
paginate:    5

authors:
 ankit_jain:
  twitter: ankneo
 sparsh_gupta:
  twitter: sparshgupta
 kushagra_agarwal:
  twitter: kushsolitary
 himanshu_kapoor:
  twitter: himkp
 kushagra_gour:
  twitter: chinchang457
 vivek_kishore:
  twitter: 
 rohit_yadav:
  twitter: _bhaisaab
 vaidik_kapoor:
  twitter: vaidikkapoor
 suchit_puri:
  twitter: suchitpuri

